### ISSUE TITLE
Error of calculations for IoU

### ISSUE THREAD

**Issue by GitHub-LYY** [dungnb1333/global-wheat-dection-2020#2]
Hi, I'm Yangyang Liu. 

I have found there may be errors in calculations for IoU (intersection over union). The calculations are in the bb_overlap function of dataset.py file. Specifically, you calculate the union as an area of just one bbox. But you know the right way is areas of two bboxes minus the overlap area.

I am not very sure if there are errors in your calculations for IoU (or maybe I am wrong, or maybe you use a new way to calculate the IoU). So can you interpret it or fix it?

**Comment by dungnb1333** [comment]
bb_overlap function isn't iou(Intersection over Union), this function just is Intersection over area of boxA.

**Comment by GitHub-LYY** [comment]
All right. I know it. Thanks very much!
